version: "3.8"

services:
  addon_service:
    build: .
    restart: unless-stopped
    command: python3 manage.py runserver 0.0.0.0:8004
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 1
      DEBUG: 1
      POSTGRES_HOST: postgres
      POSTGRES_DB: gravyvalet
      POSTGRES_USER: postgres
      # OSFDB_HOST: 192.168.168.167
      ALLOWED_HOSTS: 0.0.0.0,localhost
      SECRET_KEY: so-secret
      OSF_BASE_URL: "http://192.168.168.167:5000"
      OSF_API_BASE_URL: "http://192.168.168.167:8000"
    ports:
      - 8004:8004
    stdin_open: true
    volumes:
      - ./:/code:cached
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - "${POSTGRES_DATA_VOL:-postgres_data_vol}:/var/lib/postgresql/data/"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: gravyvalet

volumes:
  postgres_data_vol:
    external: false
